# Generated by Django 3.0 on 2020-05-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='restrict_comments',
            field=models.BooleanField(default=False),
        ),
    ]
