# Generated by Django 3.0 on 2020-05-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_photo',
            field=models.ImageField(default='images/download.png', upload_to='images/'),
        ),
    ]
